### ISSUE TITLE
string manipulation

### ISSUE THREAD

**Issue by arblake** [CCurl/s3#10]
Please give me a few examples of string manipulation, such as appending a character and scanning a string for a character.

**Comment by CCurl** [comment]
In s3, a string is just a sequence of bytes in the BYTE memory. I was thinking about what chars to use for string ops (since 's' is already used), but nothing intuitive came to mind immediately. Any ideas on chars for string opcodes would be warmly welcomed.

There are 2 built-in ways to create a string:

<addr>|here is a string|
x|another string|

The first takes an address and puts the string there, putting the next address after the NULL terminator on the stack.
- It is meant for supporting "dynamic" strings.

The second takes a string and puts the address the the start of the string and the length of the string on the stack.
- This one is meant to be used for "constant" strings built into words, as in ":Xx|hello world|".

Here are a few words for NULL-terminated strings ... I have more on my work computer, I can post them here tomorrow.

0(SLEN String-Len - (a--n)
:SLEN l+s10{r1c@~(l-xU^)ii11};

0(SCATC String-Cat-Char - (c a--)
:SCATC #SLEN+$%c!i0$c!;

0(SCATD String-Cat-Digit - (n a--)
:SCATD #SLEN+$#'9>(7+)'0+%c!i 0$c!;

0(SCAT String-Cat (dst src--)
:SCAT l+s2s1{r2c@~(l-xU^)r2c@r1c!i1i21};

**Comment by CCurl** [comment]
The unused chars are ?,e,g,j,o,p, and y. None of them seem intuitive for string opcodes. I suppose we could use lower-case chars under s, like 'sl' for string-length, 'ss' for string-set, and 'sc' string-cat, ...

Thoughts?

**Comment by CCurl** [comment]
Here are the words I use at work:

:PAD 0@ 150+;
:NTOC #9>(7+)'0+;
:NTOSTR l+ PAD 20+s3 0 r3c!{rB& NTOC d3 r3c! #}\r3 l-;
:STRTRUNC 0$c!;
:STRLEN 0s0{#c@~(\r0xU^)i0i#};
:STREND # STRLEN +;
:STRCATC STREND 0%ic!c!;
:STRCATD $ NTOC $ STRCATC;
:STRCAT #c@~(^) l+ STREND s2s1{r1c@r2c! i1i2 r1c@} 0s2c! l-;
:STRCPY # STRTRUNC STRCAT;
10 sB

(I don't know why it puts the strike-out through some of the response)

**Comment by CCurl** [comment]
So I added some string ops ... 👍

*** STRING OPERATIONS ***
sc    (S C--S)    Concatenate char C to the string at S (concat Char)
sd    (S D--S)    Concatenate digit D to the string at S (concat Digit)
se    (S--E)      E: address of the NULL terminator for the string at S (End)
sf    (S C--A)    A: address of first occurrence of char C in the string at S, 0 if not found (Find)
sl    (S--S N)    N: length of the string at S (Length)
so    (D S--D)    Concatenate source string at S to destination string at D (cOncat)
ss    (D S--D)    Set the destination string at D from the source string at S (Set/copy)
st    (D--D)      Truncate the string at S (Truncate)

**Comment by arblake** [comment]
I am reading the serial port with this:
0( open and read file)

:SECONDS 1000 * xW ;

:DISPLAY , ;

1000#|/dev/ttyUSB0| xS $0fO #~( " device not found " xQ)
 xS  $ $
 
{#  fR  # ($ DISPLAY) }
 5 SECONDS
 
 " Buffer empty or end of file "
fC xQ

and it works:
$ ./s3 file.test 
(1000 1013)(1013 93865502553264)CPS, 0, CPM, 28, uSv/hr, 0.15, SLOW

CPS, 0, CPM, 28, uSv/hr, 0.15, SLOW

CPS, 1, CPM, 29, uSv/hr, 0.16, SLOW
 If I try to create an new string between the two $s , i.e. $ |this is a string|$
I get this:
~/s3$ ./s3 file.test 
Segmentation fault (core dumped)
Not even the first stack list.

**Comment by CCurl** [comment]
I would take advantage of the built-in registers to keep the stack clean.
Something more along these lines ... what does this give you?
0(-------------------------------------------)
0(rV: start of variables)
0(rP: port handle)

:SECONDS 1000 * xW;
:DISPLAY , ;
:READF {rP fR~(\xU^) DISPLAY 1};

0@1000+ sV 
rV#|/dev/ttyUSB0|sV xS 0fO sP rP~( " device not found " xQ)
xS rV#|string 2|sV s2 xS

READF 5 SECONDS
r2 "-2nd string: %s-"
" Buffer empty or end of file "
rP fC xQ
0(-------------------------------------------)

**Comment by arblake** [comment]
It works:
adrian@adrian-hp:~/s3$ ./s3 serial.read 
(1064)()()CPS, 1, CPM, 5, uSv/hr, 0.02, SLOW

CPS, 0, CPM, 5, uSv/hr, 0.02, SLOW

CPS, 1, CPM, 6, uSv/hr, 0.03, SLOW

CPS, 0, CPM, 6, uSv/hr, 0.03, SLOW

Thanks, I am learning. Now to use the data and then apply to other devices.

**Comment by CCurl** [comment]
Excellent! I'll go ahead and close this issue then.
