### ISSUE TITLE
String to Integer

### ISSUE THREAD

**Issue by arblake** [CCurl/s3#14]
I think your string to Integer  routine broke in the last update.

**Comment by CCurl** [comment]
OK ... can you provide an example of what is breaking for you? I haven't made any changes to s3 in a while.

**Comment by arblake** [comment]
Here:
0( BTWI: n l h -- f ... Between-Inclusive )
:BTWI l+ s3 s2 s1 r1 r2 <~ r1 r3 >~ b& l-;

0( STOI: a--n ... StringToInteger )
:STOI l+ s1 0 {10* r1 c@ '0- + i1 r1 c@ '0'9 xS BTWI} l-;

x| 234| \  STOI . xQ

If there are leading spaces then it fails. I can possibly fix that. In fixed format files there is often leading spaces.

**Comment by CCurl** [comment]
I would really recommend using the 'execute' support (xE) I added not long ago. It will ignore leading blanks automatically. Otherwise, you'll need to skip the leading blanks manually.

This should skip leading blanks:
0( SLS: a1--a2 ... Skip leading blanks )
:SLS #c@32=(^)1+SLS;

![image](https://user-images.githubusercontent.com/14334380/222021095-d45a2b37-69ae-4ea8-9f49-b0b9ea90c737.png)
![image](https://user-images.githubusercontent.com/14334380/222022231-20ff473a-15fa-468f-ab71-663ae06d3a05.png)

**Comment by arblake** [comment]
Thanks
