### ISSUE TITLE
arm compile and arrays

### ISSUE THREAD

**Issue by arblake** [CCurl/s3#15]
Hi,
I successfully compiled s3 on an arm computer with Debian OS. I needed to install clang. There were just a few warnings.
My next task is to create a storage array for under 50 numbers.

**Comment by CCurl** [comment]
What were the warnings?

**Comment by arblake** [comment]
Here are warnings:
s3.cpp:30:63: warning: format specifies type 'long' but the argument has type 'cell_t' (aka 'long long') [-Wformat]
void X() { u=STB(p-1); if (u) { printStringF("-IR %ld (%c)?", u, (char)u); } p = 0; }
                                                  ~~~         ^
                                                  %lld
s3.cpp:115:71: warning: format specifies type 'long' but the argument has type 'cell_t' (aka 'long long') [-Wformat]
    if ((!isUs) && fa) { printStringF("-redef:%ld to %ld,hash(%ld)-", fa, cur, fn); }
                                              ~~~                     ^~
                                              %lld
s3.cpp:115:75: warning: format specifies type 'long' but the argument has type 'cell_t' (aka 'long long') [-Wformat]
    if ((!isUs) && fa) { printStringF("-redef:%ld to %ld,hash(%ld)-", fa, cur, fn); }
                                                     ~~~                  ^~~
                                                     %lld
s3.cpp:115:80: warning: format specifies type 'long' but the argument has type 'cell_t' (aka 'long long') [-Wformat]
    if ((!isUs) && fa) { printStringF("-redef:%ld to %ld,hash(%ld)-", fa, cur, fn); }
                                                              ~~~              ^~
                                                              %lld
s3.cpp:246:54: warning: format specifies type 'long' but the argument has type 'cell_t' (aka 'long long') [-Wformat]
    else if (u == 'n') { char z[20]; sprintf(z,"%ld",POP); y=(char*)&stb[TOS]; strcat(y, z); }
                                                ~~~  ^~~
                                                %lld
./s3.h:15:18: note: expanded from macro 'POP'
#define POP      STI(s--)
                 ^~~~~~~~
./s3.h:7:18: note: expanded from macro 'STI'
#define STI(x)   st.i[x]
                 ^~~~~~~
s3.cpp:263:57: warning: format specifies type 'long' but the argument has type 'long long' [-Wformat]
        if (s<sb-1) { printStringF("-underflow at %ld-",p-1); p=0; }
                                                  ~~~   ^~~
                                                  %lld
s3.cpp:264:54: warning: format specifies type 'long' but the argument has type 'long long' [-Wformat]
        if (r<=s) { printStringF("-overflow at %ld-",p-1); p=0; }
                                               ~~~   ^~~
                                               %lld
7 warnings generated.

**Comment by CCurl** [comment]
Wow ... Windows uses 'long long' for 64-bit values, while clang on Linux Mint uses a single 'long' to mean a 64-bit value. It sounds like Debian is more like Windows on this; I would not have guessed that.

I don't like getting warnings when I build stuff (I'm weird that way), but I suppose if it runs as expected, and you don't mind the warnings, then no worries.

I am guessing changing the 'make' script to this should address the warnings if you don't need it to be a 64-bit program (adding -m32 to the clang line). -m32 tells clang to build a 32-bit program instead of a 64-bit.

clang -m32 -Ofast -os3 -lm -D_LINUX s3.cpp

**Comment by arblake** [comment]
Same errors

**Comment by CCurl** [comment]
Unfortunately, I do not have a Debian system ... I have 2 Linuxes: Ubuntu and Mint. Neither of them give any warnings.

**Comment by arblake** [comment]
Ok, I will try to solve that myself.
Any thoughts on how best to create arrays on numbers?

**Comment by CCurl** [comment]
OK, so ... there are a couple of options.

CODE/BYTE memory is separate from CELL memory. This means that we don't have to worry about stomping on our code when working with CELL data.

What I like to do is initialize rV to to 100, because the addresses [0-99] are used for the stack and the registers. That way, I can use rV to keep track of the last allocated address for variables.

s3 has a way to define constants, with the :vXXX; syntax. EG - 12345:vARY; will set vARY to 12345. This is just a number and can be used as an address for whatever. So we can use that as the start address for an array of CELLs.

So we can do something like this to allocate space for, say 50, CELLs:

100 sV
rV :vARRAY;
rV 50+ sV

Now vARRAY pushes 100, and rV is now 150, so we have allocated addresses 100-149 for our array. Array index 0 will be address vARRAY+0 = 100, and array index 49 will be address vARRAY+49 = 149. So, vARRAY+<index> gives us the storage address.

:SVAL 0(n i--) vARRAY+!;
:GVAL 0(i--n)  vARRAY+@;

The above is, if you will, a "general-purpose" way to manage arrays that doesn't use the built-in registers. If you have an unused register that you can (and want to) use for the start address of the array, you can use it and do something more like this:

0( rV is the next free address )
100 sV

0( rA is the start address for our array of numbers )
rV sA 50 rV + sV

0( SVAL: N I-- : Set array entry I to N )
:SVAL rA+!;

0( GVAL: I--N : Get array entry I )
:GVAL rA+@;

Of course, you don't really need the SVAL and GVAL functions, you could just do <index>rA+! and <index>rA+@ too.

I hope that helps.

**Comment by arblake** [comment]
Good comments and works well, thanks
